### ISSUE TITLE
The FTP site didn't work.

### ISSUE THREAD

**Issue by xiaoxihe** [RebeccaFine/benchmarker#1]
Thank you for sharing your tool.
For your given test, we need to download data from FTP site, as follows: 

/web/ftp/outgoing/benchmarker_data/ * Binarized gene sets (*_DEPICTGenes_Ensembl_depictAndGtexGeneIntersection.txt) * Gene window files (gene_window_depict_and_gtex_gene_intersection_50kb.tar.gz) * MAGMA .annot file (depictAndGtexGeneIntersection_noMHC.gene.loc, depictAndGtexGeneIntersection_noMHC.gene.annot).

I entered this site in both " browserr" and " my computer". But it didn't work like these below. Can you help me?

![image](https://user-images.githubusercontent.com/49421269/57824895-2be6ea80-77cf-11e9-8e32-996185439c5b.png)

![image](https://user-images.githubusercontent.com/49421269/57824928-4d47d680-77cf-11e9-9303-6b96a1c3e622.png)

Looking forward to your reply!

**Comment by RebeccaFine** [comment]
Thank you for letting me know! I had the wrong path listed, sorry about that -- I've replaced it with the correct link. If it prompts you for a username and password (which it shouldn't, but I think the Broad FTP site is having some issues today), just enter "ftp" for username (password left blank) and you should be good to go. If that doesn't work, it may just take a few days for them to resolve the issue. Thanks for your patience!

**Comment by xiaoxihe** [comment]
Thank you very much for your reply. The FTP site worked well. But I didn't find another data source, such as "Download MAGMA and assciated data (1kg/g1000*)" and so on. Can you showed the data source name and corrected web site together? It may help us to use your tool easily.

**Comment by RebeccaFine** [comment]
The MAGMA data (1kg/g1000*) is under the "Reference data" tab on the MAGMA website (https://ctg.cncr.nl/software/magma). It's the download link next to the European population (assuming your data is European, of course). And their .annot data is in the "Auxiliary files" table, with the download next to "Gene locations, build 37." I'll update the README with more specific directions; does that help? Was that all the files you couldn't find?
